spring:
  application:
    name: dungeon-walker-engine

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
    env:
      show-values: ALWAYS
    configprops:
      show-values: ALWAYS

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:info}
    org:
      apache:
        kafka: ${LOGGING_LEVEL_KAFKA:warn}
    momomomo:
      dungeonwalker:
        engine:
          startup: ${LOGGING_DW_STARTUP:debug}
          transport: ${LOGGING_DW_TRANSPORT:debug}
          core: ${LOGGING_DW_CORE:debug}
          domain: ${LOGGING_DW_DOMAIN:debug}
