spring:
  application:
    name: dungeon-walker-ws-server

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
    env:
      show-values: ALWAYS
    configprops:
      show-values: ALWAYS

logging:
  level:
    root: info
    org:
      apache:
        kafka:
          clients:
            NetworkClient: warn
    momomomo:
      dungeonwalker:
        wsserver:
          startup: debug
          transport: debug
          core: debug
          domain: debug
