kafka:
  topic:
    game-engine:
      inbound: "game-engine-consumer-topic"
      outbound: "game-engine-producer-topic"

spring:
  kafka:
    consumer:
      group-id: engine-consumer-group
      auto-offset-reset: auto.offset.reset:earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: momomomo.dungeonwalker.contract.serializer.client.ClientRequestDeserializer
      enable-auto-commit: false
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
      concurrency: 3
      poll-timeout: 3000
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: momomomo.dungeonwalker.contract.serializer.engine.EngineMessageSerializer
      acks: 1
      retries: 3
