websocket:
  endpoint: /ws-endpoint
  allowed-origin-patterns: "*"

kafka:
  topic:
    outbound:
      game-engine: "game-engine-consumer-topic"

spring:
  kafka:
    producer:
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
