websocket:
  endpoint: /ws-endpoint
  allowed-origin-patterns: "*"

kafka:
  topic:
    outbound:
      game-engine: "game-engine-consumer-topic"

spring:
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: momomomo.dungeonwalker.contract.serializer.ProtoSerializer
      acks: 1
      retries: 3
